### ISSUE TITLE
Interest in joining the Tidier organization?

### ISSUE THREAD

**Issue by kdpsingh** [jdiaz97/Harbest.jl#19]
Hi @jdiaz97,

I’m one of the owners of the Tidier organization (https://github.com/TidierOrg), where we are trying to bring the comforts of R’s tidyverse to Julia.

So far, we have built 100% Julia implementations of large chunks of dplyr, tidyr, ggplot2, stringr, lubridate, and forcats.

If you’re interested in joining Tidier and/or bringing along this package (TidierVest?), would love to have you. If not, no worries and feel free to close this issue.

**Comment by jdiaz97** [comment]
Sounds good, I'm in.

**Comment by jdiaz97** [comment]
How do we proceed?

**Comment by kdpsingh** [comment]
Awesome, I just added you as a member of TidierOrg on GitHub.

Can you transfer the repository to https://github.com.TidierOrg and rename it to "TidierVest.jl" (just for consistency w/ other package names)?

You should still have direct control over commits to it.

I can help with renaming it and also on the package registry.

**Comment by kdpsingh** [comment]
Here are instructions on how to transfer: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by kdpsingh** [comment]
(Alternatively, if you'd like to keep this repo here, I can also clone this repo and host a cloned version on TidierOrg, with the idea being that further updates would get pushed there.)

Totally up to you, and again no pressure if you want to leave it here.

**Comment by kdpsingh** [comment]
Let me know if still interested in either moving or cloning this repo within the Tidier org. Happy to help if still interested.

**Comment by jdiaz97** [comment]
Hello! Sorry for the delay
I decided to clone and I'll maintain ofc
https://github.com/TidierOrg/TidierVest.jl
Unsure if it's better to "import code" or just push all the code.

**Comment by kdpsingh** [comment]
All good, and welcome!

Feel free to set it up as a new repo (so it gets its own UUID) and push your code there.

You can also just push the code and update the UUID manually.

It's easy to generate a new UUID. See here: https://stackoverflow.com/questions/69945658/how-to-create-a-uuid-for-a-julia-package

**Comment by kdpsingh** [comment]
Lastly, here's the easiest way of cloning a repo while preserving its commit history: https://dev.to/ismailpe/duplicating-a-github-repo-with-history-3223

I used this when branching off TidierData.jl from Tidier.jl as its own repo.
